version: "3.9"
services:
  db:
    container_name: storage_db
    image: mysql
    environment:
      MYSQL_DATABASE: storage_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306"
  spring:
    container_name: cloudservice_app
    image: fjd_cloudservice
    build:
      context: .
      dockerfile: back.Dockerfile
    environment:
      DATASOURCE_URL: jdbc:mysql://db:3306/storage_db
      DATASOURCE_USER: user
      DATASOURCE_PASSWORD: user
      SERVER_CONTEXT_PATH: /cloud
    ports:
      - "8081"
    depends_on:
      - db
  front:
    container_name: nginx_front
    image: fjd_cloud_vue
    build:
      context: .
      dockerfile: front.Dockerfile
    ports:
      - "80:80"
    depends_on:
      - spring

